//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostcodeData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostcodeData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataConverter.PostcodeData", typeof(PostcodeData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode;Plaats
        ///1011AB;
        ///1011AC;
        ///1011AE;
        ///1011AG;
        ///1011AH;
        ///1011AJ;
        ///1011AM;
        ///1011AN;
        ///1011AP;
        ///1011AR;
        ///1011AS;
        ///1011AT;
        ///1011AV;
        ///1011AW;
        ///1011AX;
        ///1011AZ;
        ///1011BA;
        ///1011BB;
        ///1011BC;
        ///1011BD;
        ///1011BG;
        ///1011BH;
        ///1011BJ;
        ///1011BK;
        ///1011BL;
        ///1011BM;
        ///1011BN;
        ///1011BP;
        ///1011BR;
        ///1011BS;
        ///1011BT;
        ///1011BV;
        ///1011BW;
        ///1011BX;
        ///1011BZ;
        ///1011CA;
        ///1011CB;
        ///1011CC;
        ///1011CD;
        ///1011CE;
        ///1011CH;
        ///1011CJ;
        ///1011CK;
        ///1011CL;
        ///1011CM;
        ///1011CN;
        ///1011CR;
        ///1011CS;
        ///1011CT;
        ///1011CV;
        ///1011CW;
        ///1011CX;
        ///1011CZ;
        ///1011DB;
        ///1011DC;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string postcodesEnPlaats {
            get {
                return ResourceManager.GetString("postcodesEnPlaats", resourceCulture);
            }
        }
    }
}
